server:
  port: 8080
  servlet:
    context-path: /planify

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/planify"
    username: root
    password: Thangbf2005@

jpa:
  hibernate:
    ddl-auto: none
  show-sql: true

jwt:
  signerKey: "1TjXchw5FLoESb63Kc+DFhTARvpWL4jUGCwFGWxUG5SIf/1y/LgJxHnMqaF6A/ij"

